# Generated by Django 3.0.6 on 2020-06-23 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=-1)),
                ('access', models.IntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Paid')], default=0)),
                ('accessKey', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('access', models.IntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Paid')], default=0)),
                ('accessKey', models.TextField(blank=True, default='')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(blank=True, to='material.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestSeriesResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.TestSeries')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_results', models.ManyToManyField(to='material.TestResult')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('D', 'Descriptive'), ('O', 'One_Option_Correct'), ('M', 'Multu_Option_Correct'), ('F', 'Fill'), ('ON', 'One_Option_Correct_N'), ('MN', 'Multu_Option_Correct_N'), ('MP', 'Multu_Option_Correct_P'), ('MNP', 'Multu_Option_Correct_NP')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='material/question')),
                ('answer', models.TextField(blank=True)),
                ('marks', models.IntegerField(default=0)),
                ('jsonChoices', models.TextField(blank=True)),
                ('parent_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Test')),
            ],
        ),
    ]
