# Generated by Django 3.0.6 on 2020-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_testresult_fer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='fer_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='questions',
            field=models.TextField(default=''),
        ),
    ]
